import "server-only";
import crypto from "node:crypto";
import fs from "node:fs/promises";
import path from "node:path";
import { DeleteObjectCommand, GetObjectCommand, PutObjectCommand, S3Client } from "@aws-sdk/client-s3";
import { getSignedUrl } from "@aws-sdk/s3-request-presigner";
import { appError } from "./errors";
import { SCREENSHOT_KEY_PATTERN } from "./validation";
import { log } from "./log";

export const MAX_UPLOAD_BYTES = 5 * 1024 * 1024;
export const ALLOWED_MIME = ["image/jpeg", "image/png", "image/webp"] as const;

const EXTENSION: Record<string, string> = {
  "image/jpeg": "jpg",
  "image/png": "png",
  "image/webp": "webp",
};

const MIME_BY_EXTENSION: Record<string, string> = {
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

/** Keys are generated by this module; anything else must never reach the filesystem. */
const KEY_PATTERN = SCREENSHOT_KEY_PATTERN;

/**
 * Where screenshots live when no S3-compatible bucket is configured. Deliberately
 * outside `public/`, so nothing here is ever served as a static asset — the only
 * way in is the admin-authenticated screenshot route.
 */
const LOCAL_ROOT = path.join(process.cwd(), ".storage");

export type StorageDriver = "s3" | "local";

/**
 * Local disk is a development convenience only. It does not survive a serverless
 * deploy (Vercel, Lambda and friends have an ephemeral, per-instance filesystem),
 * so production must set STORAGE_*.
 */
export function storageDriver(): StorageDriver {
  const { STORAGE_BUCKET, STORAGE_ACCESS_KEY, STORAGE_SECRET_KEY } = process.env;
  return STORAGE_BUCKET && STORAGE_ACCESS_KEY && STORAGE_SECRET_KEY ? "s3" : "local";
}

/** Magic bytes. The browser-supplied Content-Type is a hint, never proof. */
function sniffMime(bytes: Uint8Array): string | null {
  if (bytes.length < 12) return null;
  if (bytes[0] === 0xff && bytes[1] === 0xd8 && bytes[2] === 0xff) return "image/jpeg";
  if (bytes[0] === 0x89 && bytes[1] === 0x50 && bytes[2] === 0x4e && bytes[3] === 0x47) return "image/png";
  const riff = String.fromCharCode(...bytes.slice(0, 4));
  const webp = String.fromCharCode(...bytes.slice(8, 12));
  if (riff === "RIFF" && webp === "WEBP") return "image/webp";
  return null;
}

let cachedClient: S3Client | null = null;

function client(): S3Client {
  if (cachedClient) return cachedClient;
  const { STORAGE_ENDPOINT, STORAGE_ACCESS_KEY, STORAGE_SECRET_KEY, STORAGE_REGION } = process.env;
  if (!STORAGE_ACCESS_KEY || !STORAGE_SECRET_KEY) throw new Error("Storage credentials are not configured");
  cachedClient = new S3Client({
    region: STORAGE_REGION || "auto",
    endpoint: STORAGE_ENDPOINT || undefined,
    forcePathStyle: Boolean(STORAGE_ENDPOINT),
    credentials: { accessKeyId: STORAGE_ACCESS_KEY, secretAccessKey: STORAGE_SECRET_KEY },
  });
  return cachedClient;
}

function bucket(): string {
  const value = process.env.STORAGE_BUCKET;
  if (!value) throw new Error("STORAGE_BUCKET is not configured");
  return value;
}

/** Resolve a key to an absolute path, refusing anything that escapes the root. */
function localPath(key: string): string {
  if (!KEY_PATTERN.test(key)) throw appError("NOT_FOUND", "That payment screenshot is not available.");
  const full = path.resolve(LOCAL_ROOT, key);
  if (full !== path.normalize(full) || !full.startsWith(LOCAL_ROOT + path.sep)) {
    throw appError("NOT_FOUND", "That payment screenshot is not available.");
  }
  return full;
}

/**
 * Validates and stores a payment screenshot. Returns the object key; the key alone
 * grants no access to the image.
 */
export async function storePaymentScreenshot(file: File): Promise<{ key: string; mime: string; size: number }> {
  if (file.size === 0) throw appError("UPLOAD_INVALID", "The selected file is empty.");
  if (file.size > MAX_UPLOAD_BYTES) {
    throw appError("UPLOAD_INVALID", "That image is larger than 5MB. Please upload a smaller screenshot.");
  }

  const bytes = new Uint8Array(await file.arrayBuffer());
  // Re-check the real length: a lying Content-Length must not slip past the size gate.
  if (bytes.byteLength > MAX_UPLOAD_BYTES) {
    throw appError("UPLOAD_INVALID", "That image is larger than 5MB. Please upload a smaller screenshot.");
  }

  const sniffed = sniffMime(bytes);
  if (!sniffed || !(ALLOWED_MIME as readonly string[]).includes(sniffed)) {
    throw appError("UPLOAD_INVALID", "Please upload a JPG, PNG or WebP screenshot.");
  }

  const key = `payment-screenshots/${new Date().toISOString().slice(0, 10)}/${crypto.randomUUID()}.${EXTENSION[sniffed]}`;

  try {
    if (storageDriver() === "local") {
      const full = localPath(key);
      await fs.mkdir(path.dirname(full), { recursive: true });
      await fs.writeFile(full, bytes);
    } else {
      await client().send(
        new PutObjectCommand({
          Bucket: bucket(),
          Key: key,
          Body: bytes,
          // Store the sniffed type, not the one the browser claimed.
          ContentType: sniffed,
          ContentDisposition: "inline",
          CacheControl: "private, max-age=0, no-store",
        }),
      );
    }
  } catch (err) {
    log.error("screenshot_upload_failed", { err, driver: storageDriver(), size: bytes.byteLength });
    throw appError("UPLOAD_FAILED");
  }

  return { key, mime: sniffed, size: bytes.byteLength };
}

/**
 * Removes one stored screenshot. Used by the retention job once a booking is long
 * past: the payment record (amount, who approved it, when) is kept forever, only
 * the image goes.
 *
 * Deleting something already gone is not an error — the job must be safe to run
 * twice.
 */
export async function deletePaymentScreenshot(key: string): Promise<void> {
  if (!KEY_PATTERN.test(key)) throw appError("NOT_FOUND", "That payment screenshot is not available.");

  if (storageDriver() === "local") {
    try {
      await fs.unlink(localPath(key));
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
    }
    return;
  }

  await client().send(new DeleteObjectCommand({ Bucket: bucket(), Key: key }));
}

export type ScreenshotAccess =
  | { kind: "redirect"; url: string }
  | { kind: "bytes"; body: Uint8Array; contentType: string };

/**
 * How an authenticated admin gets at one screenshot.
 *
 * S3 returns a signed URL that expires in minutes; local disk returns the bytes to
 * stream back. Either way the caller has already proved it holds an admin session —
 * the image is never reachable without one.
 */
export async function getScreenshotAccess(key: string, expiresInSeconds = 300): Promise<ScreenshotAccess> {
  // Checked for both drivers, not just the filesystem one: a malformed key must
  // never be handed to the bucket as a signed-URL target either.
  if (!KEY_PATTERN.test(key)) throw appError("NOT_FOUND", "That payment screenshot is not available.");

  if (storageDriver() === "local") {
    const full = localPath(key);
    try {
      const body = await fs.readFile(full);
      const extension = key.split(".").pop() ?? "";
      return { kind: "bytes", body: new Uint8Array(body), contentType: MIME_BY_EXTENSION[extension] ?? "application/octet-stream" };
    } catch {
      throw appError("NOT_FOUND", "That payment screenshot is no longer available.");
    }
  }

  const url = await getSignedUrl(client(), new GetObjectCommand({ Bucket: bucket(), Key: key }), {
    expiresIn: expiresInSeconds,
  });
  return { kind: "redirect", url };
}
